site_name: "GEROcuidado"
repo_name: "2024-1-GEROcuidado-Doc"
repo_url: "https://github.com/fga-eps-mds/2024-1-GEROcuidado-Doc"
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.pat
    - navigation.sections
    - navigation.expand
  language: pt
  logo: "assets/gero.png"
  favicon: "assets/favicon.ico"
  palette:
    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: "#fff"
    accent: "#0B4D9B"

extra_css:
  - stylesheets/styles.css

nav:
  - Home: index.md
  - Planejamento:
    - EAP: planejamento/eap.md
    - Quadro de Disponibilidade: planejamento/quadro_de_disponibilidade.md
    - Quadro de Conhecimento: planejamento/quadro_de_conhecimentos.md
    - Quadro de Pareamento: planejamento/quadro_de_pareamento.md
    - Plano de Gestão de Custos: planejamento/planoDeCusto.md
    - Plano de Gestão de Riscos: planejamento/plano_de_ger_riscos.md
    - Plano de Qualidade: planejamento/plano_de_qualidade.md
    - Plano de Comunicação: planejamento/plano_de_comunicacao.md
    - Metodologias: planejamento/metodologia.md
    - Padrões da Comunidade: planejamento/padroes_da_comunidade.md
  - Gestão do Projeto:
    - Protótipo: produto/prototipo/prototipo.md
    - Backlog: gestaoDoProjeto/backlog.md
    - Documento de Arquitetura: gestaoDoProjeto/arquitetura.md
    - Ferramentas: gestaoDoProjeto/ferramentas.md
    - Documento de Banco de Dados: gestaoDoProjeto/doc_banco.md
    - Guia de Estilo: gestaoDoProjeto/estilo.md
    - Guia de Contribuição: gestaoDoProjeto/guia_contribuicao.md
    - Código de Conduta: gestaoDoProjeto/codigo_de_conduta.md
  - Lean Inception:
    - Lean Inception: lean_inception/lean_inception.md
    - Kick-off: lean_inception/kickoff.md
    - Dia 1: lean_inception/dia_1.md
    - Dia 2: lean_inception/dia_2.md
    - Dia 3: lean_inception/dia_3.md
    - Dia 4: lean_inception/dia_4.md
  - Dojôs:
    - Dojô Git/GitHub: dojos/git.md
    - Dojô Metodologias Ágeis: dojos/metodologias_ageis.md
    - Guia de instalação WSL2: dojos/guia_instalacao_wsl2.md
  - Semanas e sprints:
    - Semana 1:
      - Resumo semana 1: semanas/semana_1/resumo_semana_1.md
    - Semana 2:
      - Reunião Geral 27/03: semanas/semana_2/reuniao_geral_27_03.md
    - Semana 3:
      - Reunião Geral 03/04: semanas/semana_3/reuniao_po_03_04.md
      - Reunião Geral 04/04: semanas/semana_3/reuniao_po_04_04.md
    - Semana 4:
      - Reunião Geral 10/04: semanas/semana_4/reuniao_po_10_04.md
    - Semana 5:
      - Reunião Geral 19/04: semanas/semana_5/reuniao_geral_19_04.md
      - Reunião Geral 24/04: semanas/semana_5/reuniao_geral_24_04.md
      - Reunião Geral 17/07: semanas/semana_5/reuniao_geral_17_07.md
    - Sprint 1:
      - Reunião Geral 24/07: semanas/semana_6/reuniao_geral_24_07.md
      - Planning: sprints/sprint_1/planning.md
      - Review: sprints/sprint_1/review.md


plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
